controller_manager:
  ros__parameters:
    update_rate: 500  # Hz
    use_sim_time: true 

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    steering_controller:
      type: position_controllers/JointGroupPositionController

    wheel_velocity_controller:
      type: velocity_controllers/JointGroupVelocityController

steering_controller:
  ros__parameters:
    joints: 
      - base_front_left_steering_joint
      - base_front_right_steering_joint

wheel_velocity_controller:
  ros__parameters:
    joints:
      - base_rear_left_wheel_joint
      - base_rear_right_wheel_joint
